---
- hosts: all
  become: true
  tasks:
  
  - name: install latest python3 and pip3
    apt:
      name:
        - python3
        - python3-pip
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install latest python3 and pip3 for CentOS
    yum:
      name:
        - python
        - python-pip
      state: present
    when: ansible_distribution == "CentOS"
   

  - name: pip3 as default pip
    shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
  - name: python3 as default python
    shell: update-alternatives --install /usr/bin/phyton python /usr/bin/python3 10

  - name: install java open-jdk
    apt:
      name: default-jre
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install java open-jdk
    yum:
      name: java-11-openjdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: message of the day
    copy:
      content: " \n"
      dest: /etc/motd

  - name: disable motd
    file:
      dest: "/etc/update-motd.d/"
      mode: "u-x,g-x,o-x"
      state: directory
      recurse: yes

  - name: create user
    user: 
      name: "reponte"
      comment: ""
      shell: /bin/bash
